blank_issues_enabled: false
contact_links:
  - name: New Features 🚀
    url: https://github.com/PROJECT-PIPLUP/lounas-hub/issues/new?assignees=&labels=&template=new.md&title=%5BNew%5D%3A+
    about: For developers 🐧
  - name: Issues to be fixed 🚑
    url: https://github.com/PROJECT-PIPLUP/lounas-hub/issues/new?assignees=&labels=&template=issue.md&title=%5BIssue%5D%3A+
    about: For developers 🐧
